<a href="https://colab.research.google.com/github/Sonsylvain/Sonsylvain.github.io/blob/main/sets_and_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#                                                                Creating dictionaries from sequences

# joinning sequences by defining renge of sequence
key_list = list(range(5))                          # This only works with a defined range, once if exceeds it just provides an Error " Out of range"
value_list = list(reversed(range(5)))              # and how to solve this once we have extra values within value set-- with use Default value method mentioned in 3rd cell
def zip(key_list, value_list):
    result = {}
    for i in range(len(key_list)):
        result[key_list[i]] = value_list[i]
    return result
mapping = dict(zip(key_list, value_list))
print(mapping) # Output: {0: 4, 1: 3, 2: 2, 3: 1, 4: 0}



# Default Values
key_list = list(range(5))
value_list = list(reversed(range(5)))
def zip(key_list, value_list, default = None):
    result = {}
    for i in range(len(key_list)):
      if i > len(value_list):
        result[key_list[i]] = value_list[i]
      else:
        result[key_list[i]] = default
    return result
mapping = dict(zip(key_list, value_list))
print(mapping) # Output: {0: None, 1: None, 2: None, 3: None, 4: None}




# joining sequnces with a defined set of objects
keys = ['name', 'age', 'city']
values = ['Alice', 25, 'New York']
def zip(keys, values):
    result = {}
    for i in range(len(keys)):
        result[keys[i]] = values[i]
    return result
person = dict(zip(keys, values))
print(person)  # Output: {'name': 'Alice', 'age': 25, 'city': 'New York'}




words = ["apple", "bat", "bar", "atom", "book", "car", "dog"]
by_letter = {}
for word in words:
  letter = word[0]# when you try to display an index in a set of array, every index presents the first leter of each element in the array.
  if letter not in by_letter:
    by_letter[letter] = [word]
  else:
    by_letter[letter].append(word)
print(by_letter) # output: {'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}  dictionary from sequence by grouping keys to their corresponding values.

from collections import defaultdict  # collection mudule: The built-in collections module has a useful class, defaultdict, which makes this even easier.
by_letter = defaultdict(list) # this sets automaical keys to specified values without any a manual process defined earlier
for word in words:
  by_letter[word[0]].append(word)
print(by_letter)




hash("string")
hash((1, 2, (2, 3))) # hash values


d = {}
d[tuple([1, 2, 3])] = 5 # assigning a key(list) to a certain value by first conveting it into a hash object
d



# SET: is an ordered collection of unique elements. A set can be  created in two ways: via the set function or via a set literal with curly braces:
set_curly = {2, 2, 2, 1, 3, 3, 7, 7} # set presented by curly braces
set_function = set([2, 2, 2, 1, 3, 3, 7, 7]) # set presented by function of set
print(set_curly)
print(set_function)

#Union
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}
union = a.union(b)
print(union)

intersect = a.intersection(b)
print(intersect)

notin = a.difference_update(b)
print(notin)

# python SET operations
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}
a|b # a.union(b)
a&b # a.intersection(b)
a.add(9) # adding an element
a.remove(9) # removing an element
a |= b # a.update(b) : set the contents of a to be the union of the elements a and b
a &= b # a.intersection_update(b) : set the contents of a to be the intersection of a and b
a-b # a.difference(b): elements in a that are not in b
a-=b # a.difference_update(b) : set a to be the difference of a and b
a^b # a.symmetric_difference(b) : elements in a or b but not both
a^=b # a.symmetric_difference_update(b) : set a to be the symmetric difference of a and b
a.isdisjoint(b) # True if a and b have no elements in common
a.issubset(b) # True if a is a subset of b
a.issuperset(b) # True if a is a superset of b


a_set = {1, 2, 3, 4, 5}
{1, 2, 3}.issubset(a_set)
a_set.issuperset({1, 2, 3})
{1, 2, 3} == {3, 2, 1}

# making sets have the same value
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}
a |= b
a &= b

a == b


#             Built-In Sequence Functions
# enumerate : it is common when iterating over a sequence to want to keep track of the index of the current item
collection = ['apple', 'banana', 'cherry']

index = 0
for value in collection:
    print(f"Index: {index}, Value: {value}") # it output three iterated vlues and their index, but this is manually generated, lets see with the use of enumerate
    index += 1
# use of Enumerate : The enumerate() function provides a cleaner way to achieve the same result by automatically tracking the index.
for index, value in enumerate(collection):
    print(f"Index: {index}, Value: {value}")


# sorted : the sorted function returns a new sorted liat from the elements of any sequence
sorted([7, 1, 2, 6, 0, 3, 2]) # it can sort numbers
sorted(["even", "odd", "abbas", "bold", "cold"]) # ot can sort string of alphabets
sorted("horse race") # it can sort string

# zip : “pairs” up the elements of a number of lists, tuples, or other sequences to create a list of tuples
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
zipped = zip(seq1, seq2)
list(zipped)
# A common use of zip is simultaneously iterating over multiple sequences, possibly also combined with enumerate:
for index, (a, b) in enumerate(zip(seq1, seq2)):
    print(f"{index}: {a}, {b}")

# reversed: iterates over the elements of a sequence in reverse order:
list(reversed(range(10))) # you must turn into a list to see the output

# using unifying two lists into a set and sort them into a dictionary with respect to their letters and having a key letter of their group
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
set_1 = set(seq1)
set_2 = set(seq2)
unified = set_1.union(set_2)

dict_all = {}
for word in unified:
  letter = word[0]
  if letter not in dict_all:
    dict_all[letter] = [word]
  else:
    dict_all[letter].append(word)
print(dict_all)

In [ ]:
 #                                                      Comprehensions(Dictionaries, Sets)

# A dictionary comprehension, allows you to create a dictionary from iterable in a single line using the following syntax:
#dict_comp =  {key-expr: value-expr for value in collection if condition}
# example:
numbers = [1, 2, 3, 4, 5]
dict_comp = {num: num**2 for num in numbers if num % 2 == 0}
print(dict_comp) # even numbers comprehension dictionary with respect to their key number.

# A set comprehension, same way of comprehension, it also uses curly braces but fro list there is no key as we all know:
# set_comp = {expr for value in collection if condition}
# example:
set_comp = { num for num in numbers if num % 2 != 0  }
print(set_comp) # odd number comprehension set.

# 1
strings = ["apple", "hi", "dog", "banana", "cat", "a"]
unique_lengths = {len(x) for x in strings} # set comprehension into lengths at indexes of a difined collection
print(unique_lengths)
# 2
set(map(len, strings)) # alternative way to turn into length set of a collectuion

# Also we are going to create a lookup map of these strings for their locations in the list:
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

#                                               Nested List Comprehensions
# 1
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
       ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

names_of_interest = []
for names in all_data:
        enough_as = [name for name in names if name.count("a") >= 2]
        names_of_interest.extend(enough_as)
print(names_of_interest)

#2
result = [name for names in all_data for name in names
             if name.count("a") >= 2]
print(result)


{2: 4, 4: 16}
{1, 3, 5}
{1, 2, 3, 5, 6}
['Maria', 'Natalia']
['Maria', 'Natalia']


In [ ]:
# 1. Here is another example where we “flatten” a list of tuples of integers into a simple list of integers:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened
# 2. using a nested for loop instead of a liat comprehension:

flattened = []
for tup in some_tuples:
    for x in tup:
        flattened.append(x)
flattened


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Functions
def my_function(x, y):
  return x + y

# Call the function
my_function(1, 2)


3

In [ ]:
#        Functions are objects
# Suppose we are doing some data cleaning and needed to apply a bunch of transformations to the following list of strings:
# User- submitted surveys: thise are type of messy data, and lots of things need to happen to make this list of strings uniform ready foranalysis:
# stripping whitespace, removing punctuation symbols, snd standardizing proper capitalization. one way to do this is to use built in string methods along with the re standard library module for regular expressions:

import re # imported module "re" regular expression(Regex)

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()  #Remove leading/trailing spaces: getting rid of spaces at the beginning (leading) and the end (trailing) of a string while keeping the text inside unchanged.
        value = re.sub("[!#?]", "", value) # responsible for replacing patterns in strings re.sub(pattern, replacement, string), pattern: A regex pattern that specifies what to search for, replace with, wich string
        value = value.title()  # Convert to title case the leading character
        result.append(value)
    return result
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
             "south carolina##", "West virginia?"]

clean_strings(states)

# Alternative approach
def remove_punctuation(value):
    return re.sub("[!#?]", "", value)
clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

clean_strings(states, clean_ops)




['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South Carolina',
 'West Virginia']

In [ ]:
#     Anonymous (Lambda) Functions // Unkown value/Lambada

def apply_to_list(some_list, f):
      return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]

apply_to_list(ints,  lambda x: x *2)# if we try to solve the argument without using Lambade it will turn into this error "int' object is not callable" means we we tried to use an int multiplying f(x)

# As another example, suppose you wanted to sort a collection of strings by the number of distinct letters in each string:
strings = ["foo", "card", "bar", "aaaa", "abab"]
strings.sort(key=lambda x: len(set(x)))
strings




['aaaa', 'foo', 'abab', 'bar', 'card']

In [ ]:
# Generators: generators are like functions, they can return a sequence of multiple values by pausing and resuming execution each time the generator is used. To create a generator, use the yield instead of return.
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2
# When you actually call the generator, no code is immediately executed:
gen = squares()
gen
# output: <generator object squares at 0x17d5fea40>

# It is not until you request elements from the generator that it begins executing its code:
for x in squares():
  print(x, end=" ")

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [ ]:
# Genaerator Expressions
# This is a generator analogue to list, dictionary and set comprehensions. To create one, enclose what would otherwise be a list comprehension within parantheses instead of brackets:
def _make_gen():
  for x in range(100):
    yield x ** 2
gen = _make_gen()
gen

<generator object _make_gen at 0x7ba70f34f920>

In [ ]:
                                                                           # Itertools modele
# this is the most important library that has a collection of generators for many common data algorithms. For example, groupby takes any sequence and function
# grouping consecutive elements in the sequence by return value of the function.

import itertools

# Groupby
def first_letter(x):
  return x[0]

names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]

for letter, names in itertools.groupby(names, first_letter):
  print(letter, list(names)) # names is a generator


                                                                   # ERRORS AND EXCEPTION HANDLING
# Users sometimes may insert improper input which may result to Errors at the output, it is advisable to solve this when especially building functions or any type of argument, you must raise an else
# Example on functions

def attempt_float(x):
  try:
      return float(x)
  except ValueError:
    return x

print(attempt_float("1.2345")) # this is considered as proper input, it will be returned at the "try" session

print(attempt_float("something")) # this is considered as improper input, it will be reruned at the "except" session || for error handling, raising exceptions is the solution to error handling


A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']
1.2345
something


In [ ]:
                                                                   # FILES AND THE OPERATING SYSTEM

#  To open a file for reading or writing, use the built-in open function with either a
#relative or absolute file path and an optional file encoding:

path = r"C:\Users\Sylvain\Music\data.txt"
try:
    with open(path, encoding="utf-8") as f:
        for line in f:
            print(line)
except FileNotFoundError:
    print("File not found! Check the path and try again.")


#f = open(path, encoding="utf-8") # UTF-8 (Unicode Transformation Format - 8-bit) is a character encoding system that allows text to
#be stored and transmitted in a way that supports a wide range of characters from different languages, including symbols and special characters.
for line in f:
 print(line)

File not found! Check the path and try again.


NameError: name 'f' is not defined

In [19]:
# Numpy Basics: Arrays and Vectorized Computation

# 1. NumPy ndarray
import numpy as np
data1 = [[1, 2, 3, 4, 5, 6], [2, 5, 2, 1, 4, 3], [0, 1, 3, 5, 6, 7]]
array1 = np.array(data1) # coneverting the nested list into array
print(array1)
shape = print(array1.shape) # checking the size of an array.
dtype = print(array1.dtype) # checking the data type.
number_dimension = print(array1.ndim) # checking the number of dimensions.

array_zeros = np.zeros((3, 6)) # demension of zeros with aspecified shape dimension
# the data type in python if not specified in many times it will be considered as flaot64/ float point
import numpy as np

# 1️⃣ Creating a NumPy ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (matrix)
print("Original Array:\n", arr)

# 2️⃣ Checking Shape and Size
print("Shape:", arr.shape)  # (rows, columns) → (2, 3)
print("Size:", arr.size)  # Total number of elements → 6
print("Data Type:", arr.dtype)  # Data type of elements → int

# 3️⃣ Generating Special Arrays
zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
ones = np.ones((3, 2))  # 3x2 matrix of ones
identity = np.eye(3)  # 3x3 identity matrix
random_arr = np.random.rand(3, 3)  # 3x3 matrix with random numbers

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Random Array:\n", random_arr)

# 4️⃣ Accessing Elements (Indexing & Slicing)
print("Element at (1,2):", arr[1, 2])  # Second row, third column → 6
print("First row:", arr[0, :])  # First row → [1, 2, 3]
print("First column:", arr[:, 0])  # First column → [1, 4]

# 5️⃣ Mathematical Operations
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
sum_arr = arr + arr2  # Element-wise addition
product_arr = arr * arr2  # Element-wise multiplication
dot_product = np.dot(arr, arr2.T)  # Matrix multiplication

print("Sum:\n", sum_arr)
print("Product:\n", product_arr)
print("Dot Product:\n", dot_product)

# 6️⃣ Reshaping and Transposing
reshaped = arr.reshape(3, 2)  # Change shape to 3x2
transposed = arr.T  # Transpose (swap rows & columns)

print("Reshaped (3x2):\n", reshaped)
print("Transposed:\n", transposed)

# 7️⃣ Statistical Operations
print("Mean:", np.mean(arr))  # Average value
print("Max:", np.max(arr))  # Largest value
print("Min:", np.min(arr))  # Smallest value
print("Standard Deviation:", np.std(arr))  # Spread of values

# 8️⃣ Filtering with Boolean Indexing
greater_than_3 = arr[arr > 3]  # Get all elements greater than 3
print("Elements greater than 3:", greater_than_3)

# Unsigned integer and signed integer, sigend reperensets both negative and positivr integer where as
# unsigned represents positive from 0-255

# casting/converting an array from one data type to another using astype method:
arr = np.array([1, 2, 3, 4])
float_arr = arr.astype(np.float64)
print(float_arr)
float_arr.dtype
# if you have have an array of strings representing numbers, you can use astype to convert
# them to numeric form:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)
# you can also use another array's dtype atrribute:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)




[[1 2 3 4 5 6]
 [2 5 2 1 4 3]
 [0 1 3 5 6 7]]
(3, 6)
int64
2
Original Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array:
 [[0.28353322 0.8169186  0.23490441]
 [0.822468   0.19633825 0.24670034]
 [0.36616318 0.94134024 0.92959516]]
Element at (1,2): 6
First row: [1 2 3]
First column: [1 4]
Sum:
 [[ 8 10 12]
 [14 16 18]]
Product:
 [[ 7 16 27]
 [40 55 72]]
Dot Product:
 [[ 50  68]
 [122 167]]
Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Mean: 3.5
Max: 6
Min: 1
Standard Deviation: 1.707825127659933
Elements greater than 3: [4 5 6]
[1. 2. 3. 4.]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
# Arithmetic with NumPy Arrays
# Arrays are important because they enable you to express batch operations on data
#without writing any for loops. NumPy users call this vectorization.
list1 = [[1, 2, 3, 4, 5, 6], [2, 6, 7, 8, 8, 0]]
list2 = [[4, 8, 6, 7, 2, 7], [4, 7, 5, 4, 3, 6]]
array_arithmetic2 = np.array(list2)
array_arithmetic = np.array(list1)
array_arithmetic * array_arithmetic
array_arithmetic - array_arithmetic
array_arithmetic**2
1/array_arithmetic
# Comparisons between arrays of the same size yield boolean arrays:
array_arithmetic > array_arithmetic2

#  Basic Indexing and Slicing
arr = np.arange(10)
arr[5]
arr[5:8]


<ipython-input-26-e0df8e3726d8>:11: RuntimeWarning: divide by zero encountered in divide
  1/array_arithmetic


array([[False, False, False, False,  True, False],
       [False, False,  True,  True,  True, False]])

In [4]:
import numpy as np
# However you slice specific elements into an array and you mutate them,
# even if you can assign the change to the new variable the changes still affects the inital array,
# means you can not make copies of a slice, if you want so you can use copy method
random_arr = np.arange(10)
arr = random_arr[5:7] # two dots in a slice are called "bare"
arr[1] = 24
random_arr
copied = arr[0:1].copy
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] # accessing a specified nested list
arr2d[1][0]# accessing single elements


np.int64(4)